"use client"
import Header from './components/header'
import './globals.css'
import { Nunito } from 'next/font/google'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Nikolas Mello Web Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode}) {

  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        {children}  
      </body>
    </html>
  )
}
